name: Qt 5.15.2 on macOS

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '5.15.2'
        host: 'mac'
        target: 'desktop'
        arch: 'clang_64'

    - name: qmake
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: qmake

    - name: make
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: make
