name: Qt 6 on Windows

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1
 
    - name: Setup MSVC Developer Command Prompt
      uses: TheMrMilchmann/setup-msvc-dev@v2.0.0
      with:
        arch: x64

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.3.*'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'

    - name: configure
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: cmake -DQT_BUILD_EXAMPLES:BOOL=ON

    - name: make
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: cmake --build .
